### ISSUE TITLE
Parsing Error when Event has No Title

### ISSUE THREAD

**Issue by Lucas44443** [franc6/ics_calendar#125]
Hello franc,

Firstly, I want to express my appreciation for the seamless integration provided.
I encountered an issue while using a Google ICS for this integration. It seems that when an event is created without a title, the calendar fails to load, displaying a parsing error: "Failed to validate CalendarEvent: required key not provided @ data['summary']".
Upon removing the event without a title, the calendar functions normally. It would be great if this issue could be addressed in future updates.
Thank you for your attention to this matter.

**Comment by franc6** [comment]
The HA calendar no longer allows events without a title/summary. I could probably either ignore such an event, or put in a dummy title, like “no summary”. If people will weigh in with their opinions, it’s an easy change when I get some time to do the next release. Oh, or better, take the first several characters (or words) of the description?

**Comment by maxhamilius** [comment]
Hi,
Weighing in to this issue. Got the same error for a calendar I subscribe to `Failed to validate CalendarEvent: required key not provided @ data['summary']` Unfortunately I cannot edit the calendar to remove the missing data since it is automatically generated from a scheduling platform.
I really appreciate the work that has gone into this integration, looking forward to future releases.

**Comment by franc6** [comment]
Do you have an opinion on what to put in the summary? The requirement that it have something is from HA, but it's easy for me to put something in there.  I'd like to at least pretend I'm putting something useful there. :)

**Comment by maxhamilius** [comment]
I had a closer look at my calendar subscription. There are a few events without summary. In my case they could simply be ignored, or the summary could maybe replaced with a configurable string.

**Comment by jonasglass** [comment]
I have also run into this issue. If I may express my opinion here, I´d be in favor of setting a default summary, e.g. "No title"
This is how Google Calendar does it. 
I dont like dropping the events completely, because if does not allow using this integration for automated event handling from external systems which may not provide a summary/title.

**Comment by franc6** [comment]
v5.0.5 will have a hard-coded default for this.  This isn't a real fix, so I'm leaving it open for now.

**Comment by franc6** [comment]
Will be fixed in 5.1.0
