### ISSUE TITLE
Not loading Calendar

### ISSUE THREAD

**Issue by AshtonKem** [franc6/ics_calendar#182]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version: 2024.10.2

Installation Type (put an X between the square brackets for your HA):
[] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[X] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[X] x86-64

**Describe the bug**
A clear and concise description of the bug

It appears like it's double URI decoding my calendar URI, which causes obvious issues.

I entered my calendar as:

`https://outlook.office365.com/owa/calendar/<userid>@<domain>/<calendarid>/calendar.ics`, but the logs contain:

`https://outlook.office365.com/owa/calendar/<userid>%2540<domain>/<calendarid>/calendar.ics`

Given that "%40" is the URI encoding of "@", and "%25" is the URI encoding of "%", it appears like this is caused by the extension is double encoding the URI somehow.

**Comment by AshtonKem** [comment]
Interesting, an update to 2024.10.3 fixed it for me. Not clear if this is an ICS bug, a HA core bug, or a negative interaction between the two.

**Comment by franc6** [comment]
I suspect something else happened -- I'm pretty sure an update to HA couldn't have fixed anything, since there's no code from HA involved in this problem.  It's a known issue, and it's on my list of things to more properly fix.  I just have competing requests, where some want to enter an unencoded URL and others do not.
