### ISSUE TITLE
Patch-Update breaks other integrations/addons

### ISSUE THREAD

**Issue by fsedarkalex** [franc6/ics_calendar#186]
Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[X] x86-64

**Describe the bug**
Version 5.0.4 updated the icalendar library dependencies to 6.0.0 which breaks another component.
In my opinion this should be reverted and reintroduced at least as version 5.1 (better 6.0) as a major dependency jump should not be carried out in a patch-version-release in semantic versioning.
Nobody expects a patch release to updae a system-wide library

see also https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893

**Comment by Lateadapter** [comment]
same issue here with ver 5.0.4 and hacs_waste_collection;  ... (ICS calendar 5.0.3 works)

**Comment by Jirka-Eh** [comment]
Same issue here.

**Comment by franc6** [comment]
Sorry, but I'm not going to try tracking other custom integrations that might use some of the same libraries, but of different versions.  Likewise, I don't expect any other custom integration authors to track this one.

It's not ideal, but my priority is fixing the problems in this integration, which is why the requirement was bumped up.

Version 6 of the icalendar library changes how it handles time zones, specifically so it doesn't use pytz anymore.  pytz has been the source of some of the problems reported with this integration in the past, especially when HA core used an older version of pytz.  Eliminating the need for it seemed (and still seems) like a really good idea. :)  Additionally, there are still some parsing problems with icalendar version 6, so I'll continue to track updates to it as closely as I can.  Until it seems to be stable and without problems reported by multiple users (or experienced by me), I'll continue to track all the parser libraries and their dependencies.  I might pick-and-choose a little more, but as long as it doesn't break my own installation, it's fair game to me.  I also won't be updating anything but the step version number for a dependency (or a dependency of a dependency like icalendar is), unless I have to make coding changes for it.  This didn't require any code changes, as the changes to icalendar were all behind-the-scenes.  Even recurring-ical-events (which is what this integration directly uses) didn't make changes to support icalendar version 6.
