### ISSUE TITLE
Home Assistant Event for newly created calendar entries 

### ISSUE THREAD

**Issue by freddeh** [franc6/ics_calendar#189]
Dear all,

I have a question concerning newly added calendar entries. Is it possible to somehow use a newly created calendar event as a trigger in an automation? Does this integration or Home Assistant somehow fire an event for a new entry?

BR

**Comment by franc6** [comment]
That's currently not possible.  I would argue that such functionality belongs in HA, since it would them be common to all calendar platforms.  However, I suspect nobody will want to do it, since HA doesn't track the calendar events, AFAIK.  It'd be a lot of work, and probably significantly increase the resources necessary.
I can see how it would be useful, but perhaps there's another way to achieve your goal?  Do you need to know when a new event is added, or just need to know X amount of time before the new event time?  If the latter, I think it can be done with some python scripts and/or automations, but I'm not 100% certain.  You might need to use the HA API to read the calendar events yourself, and that might require an external script. :(
