### ISSUE TITLE
Latest Update Prevents Home Assistant from Starting

### ISSUE THREAD

**Issue by florianmulatz** [franc6/ics_calendar#200]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version:

Core 2024.12.2
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7

Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS

Hardware platform:
[] ARM
[X] x86-64

**Describe the bug**

Home Assistant no longer starts after installing the latest update. I can only provide the last two lines from the core-ha-log—nothing happens beyond that point:

```
2024-12-13 06:20:05.531 INFO (MainThread) [homeassistant.components.calendar] Setting up ics_calendar.calendar
2024-12-13 06:20:05.532 INFO (MainThread) [homeassistant.components.calendar] Setting up ics_calendar.calendar
```

Thx in advance

**Comment by gheydon** [comment]
Yes I got this issue as well.

**Comment by florianmulatz** [comment]
Deleting the folder ```ics_calendar``` in ```custom_components``` allows Home Assistant to start normally again.

**Comment by exnerit** [comment]
same here

**Comment by klaptafel** [comment]
Same here

**Comment by btpv** [comment]
i have the same issue on docker

**Comment by wjansenw** [comment]
+1
deleting the folder from the custom_components-folder, restart HA, downloading again from HACS but with release 5.0.4 brings you back to a working set-up

**Comment by DF3MT** [comment]
Same here, reosting from backup resolved it. waiting for new version to get it fixed

**Comment by florianmulatz** [comment]
Hi everyone,

To keep this issue clear and helpful, please avoid posting comments like "+1" or "Same here." These don't add useful information and make it harder to follow the discussion.

If you're experiencing the same issue, you can use the 👍 reaction on the main post or any relevant comments. This helps keep things organized and focused on solving the problem.

Let’s wait for feedback from the developers.

**Comment by florianmulatz** [comment]
> r from the custom_components-folder, restart HA, downloading again from HACS but with release 5.0.4 brings you back to a working set-up

5.0.4 was the previous version right? That's a practical hint! thx for that

**Comment by ericsche** [comment]
Same here, what a stressful morning... I had to do a restore.

**Comment by wjansenw** [comment]
> > r from the custom_components-folder, restart HA, downloading again from HACS but with release 5.0.4 brings you back to a working set-up
> 
> 5.0.4 was the previous version right? That's a practical hint! thx for that

correct. 

> Same here, what a stressful morning... I had to do a restore.

It is not needed to do a restore. Just disable the custom component by eg. moving the folder in /config/custom_components to a temp location outside this folder, or just deleting it and restart HA.

**Comment by threadstone83** [comment]
I have exact the same problem. My bigger problem is, HA is installed in a VM on my Synology and I don't know how I could delete the folder. Can anyone help me?

**Comment by ericsche** [comment]
> > > r from the custom_components-folder, restart HA, downloading again from HACS but with release 5.0.4 brings you back to a working set-up
> > 
> > 
> > 5.0.4 was the previous version right? That's a practical hint! thx for that
> 
> correct.
> 
> > Same here, what a stressful morning... I had to do a restore.
> 
> It is not needed to do a restore. Just disable the custom component by eg. moving the folder in /config/custom_components to a temp location outside this folder, or just deleting it and restart HA.

Damn!! I did not know that... I lost 9hours of data

**Comment by wjansenw** [comment]
> I have exact the same problem. My bigger problem is, HA is installed in a VM on my Synology and I don't know how I could delete the folder. Can anyone help me?

does this help you: https://www.home-assistant.io/docs/troubleshooting_general/

**Comment by Helllie** [comment]
Do you have Home Assistant Add-on: File editor installed ?
You can't completely delete the folder (because of hidden files) , but you can rename the folder and delete files from the folder.

Or when you have SMB services you can find the folder in your Window explorer and delete it.

**Comment by threadstone83** [comment]
@wjansenw @Helllie thank you very much. I was fast enough to navigate to the folder and delete it (it was no problem to delete it completely via filebrowser) bevor HA crashes. Now I have to look how to access the folders from windows (for the future). But for the moment the problem is solved and all works as it should be.

**Comment by Curtis777** [comment]
samer error on unraid VM

**Comment by jarooij** [comment]
Same here. I had to force HA starting in safe mode through ssh and then restore a previous backup.

**Comment by Curtis777** [comment]
> Same here, what a stressful morning... I had to do a restore.

sounds like my life! wife is away and something breaks. no freetime for me haha

**Comment by vrtareg** [comment]
Same with me, deleted the folder, restarted and then installed 5.0.4 to get HA back.
I am running it in Python 3.13.1 venv.

**Comment by arjannv** [comment]
@threadstone83  
>I have exact the same problem. My bigger problem is, HA is installed in a VM on my Synology and I don't know how I could delete the folder. Can anyone help me?

Had the same problem, on the Synology web page, I went to the Virtual Machine Manager, got to the VM and pressed "Connect". 
This opens a new tab to the console of the VM. 

type `login` to enter the host console. 

go to the addons folder: 
`cd /mnt/data/supervisor/homeassistant/custom_components`

remove the ics folder: 
`rm -r ics_calendar`

reboot the VM and you are done :)
After that you can install 5.0.4

**Comment by Hydradox** [comment]
To anyone with this problem, you can boot Home Assistant in safe mode with `core restart --safe-mode`.
Im hoping for this to be fixed, so I just disabled the entities instead of deleting the integration, rebooted again and it's working again.

**Comment by threadstone83** [comment]
> > I have exact the same problem. My bigger problem is, HA is installed in a VM on my Synology and I don't know how I could delete the folder. Can anyone help me?
> 
> Had the same problem, on the Synology web page, I went to the Virtual Machine Manager, got to the VM and pressed "Connect". This opens a new tab to the console of the VM.
> 
> type `login` to enter the host console.
> 
> go to the addons folder: `cd /mnt/data/supervisor/homeassistant/custom_components`
> 
> remove the ics folder: `rm -r ics_calendar`
> 
> reboot the VM and you are done :) After that you can install 5.0.4

@arjannv Thank you for the detailed instructions! Do you eventually also know how to access it via Windows? I'm not much of a command line person :-(

**Comment by smarthomefamilyverrips** [comment]
@franc6 I understand that this whole integration is done voluntary and in your free time what is highly appreciated 👏..... but still I can't keep from wondering how is possible that a release that brakes HA for so many of us got released in the first place? 🙄

**Comment by jlaffaye** [comment]
Is there a way to unpublish/mark as broken this version on github ?
So HACS does not discover the new version and end users are not prompted to upgrade.

**Comment by acato** [comment]
You should unpublish this release. It completely hoses the server and requires a clean reinstall and backup restore. It looks like it hangs somewhere in the network stack and prevents HAOS to talk to the network via http or https. I kept receiving push notifications, so some services were still working.

**Comment by TheZoker** [comment]
Why can a custom integration break HA this hard? 
We had that situation years ago, but then the devs implemented stuff to prevent this from happening (at least so I thought)

**Comment by ericsche** [comment]
I agree, this is strange.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alanmilinovic** [comment]
Very annoying and unbelievable that such a huge project can become dead when add-on is updated.

**Comment by Eschguy** [comment]
Yep, happened to me as well.

**Comment by franc6** [comment]
"It works for me."

Seriously, I published the 5.0.5-beta1 on Wed and installed it through HACS (I try to install the same way most users will install it), and I didn't have any trouble.  The changes between the -beta1 and final release are very minor, a change to README.md (which doesn't affect anything at all), a default string for events that don't have a summary (which I'm pretty sure can't crash anything, and certainly not at startup as the code wouldn't be called that early), and a change to pyproject.toml to fix running tests on the project in GitHub (that file isn't used by HA either). I can also say that after installing the final release, it still, "works for me".

The unit tests also were run against HA 2024.12.2, which was the latest HA release when I updated this (2024.12.3 was released today, 2024-12-13, as I write this).  Additionally, see [this HA issue](https://github.com/home-assistant/supervisor/issues/5373) which someone else mentioned.

For now, I'm going to mark 5.0.4 as the "latest release" which I think will get HACS to show that instead of 5.0.5.

For those who have this problem, please post your HA version info, how it's installed, what hardware (arm64 v x86-64) and system memory.  The HA issue is possibly a better place to collect information, but I'd like to collect what we can here first, to see if there's anything in common, especially if it's different from what's listed in the HA instance.  Some configuration info would be useful, too, especially if you use authentication or a user-agent.  Please do NOT include your actual calendar URLs or authentication information.  Just put in three X characters in place of those, as I've done below.  If you don't know where to find the info, don't worry about it.  I think I need to expose the config data in the logs, but that'll be a release after this problem is cleared up. :)

Here's my info, which is very similar to the OP:

 Core 2024.12.2
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7

4 x86-64 CPUs
8GB RAM

```json
{"created_at":"2024-09-11T17:29:37.739016+00:00","data":{"accept_header":"","advanced_connection_options":true,"connection_timeout":300.0,"days":1,"download_interval":15,"exclude":"","include":"","include_all_day":true,"name":"Meals","offset_hours":0,"parser":"rie","password":"","prefix":"","requires_auth":true,"set_connection_timeout":true,"url":"https://XXX","user_agent":"","username":""},"disabled_by":null,"discovery_keys":{},"domain":"ics_calendar","entry_id":"01J7H24CPBE567CNME6C82XAKZ","minor_version":0,"modified_at":"2024-09-11T17:40:53.363615+00:00","options":{},"pref_disable_new_entities":false,"pref_disable_polling":false,"source":"import","title":"","unique_id":null,"version":1}
```

**Comment by smarthomefamilyverrips** [comment]
@franc6 

![Screenshot_20241213_222830_Home Assistant](https://github.com/user-attachments/assets/eb06ac00-6641-436a-935e-73145938a79f)

Home Assistant Blue / Odroid N2+ 
4GB RAM

**Comment by ericsche** [comment]
Core
2024.12.1
Supervisor
2024.11.4
Operating System
14.0
Interface utilisateur
20241127.6

x86
4gb ram

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by arjannv** [comment]
I’ve got two systems with both the same issue:

HA OS in ESXi hypervisor
Home Assistant core version 2024.12.2
Supervisor version 2024.11.4
OS version 14.0
2 cores x86 and 4 GB RAM

HA OS in Synology Virtual Machine Manager
Home Assistant version 2024.12.2
Supervisor version 2024.11.4
OS version 14.0
2 cores x86 and 2 GB RAM

**Comment by MiniFido** [comment]
i need to reinstall HA before i can get it up.

**Comment by olafz** [comment]
> For those who have this problem, please post your HA version info, how it's installed, what hardware (arm64 v x86-64) and system memory.

Core 2024.12.3
Supervisor 2024.11.4
Operating System 14.0
Frontend  20241127.8

2 x86-64 CPUs
10GB RAM

> Some configuration info would be useful, too, especially if you use authentication or a user-agent.

I've removed the config entries to get Home Assistant starting again, but one example calendar I use is `https://ics.maak-agenda.nl/v2/league/formula-1-qualifiers.ics`. No specific authentication and/or User Agent configuration.

**Comment by threadstone83** [comment]
@franc6 

Core 2024.12.2
Supervisor 2024.11.4
Operating System 13.2
Frontend 20241127.7

Installed in VM (Synology Virtual Machine Manager) on Synology DS918+ with 8GB RAM (4GB for the VM) with image from HA website.

**Comment by MichaKersloot** [comment]
Just to add my experiences.
I updated ics_calendar and homeassistant core at the same time and found homeassistant didn't start. In the homeassistant.log I saw the logging of MainThread stopped after 
`homeassistant` homeassistant[445]: 2024-12-13 15:28:45.353 DEBUG (MainThread) [custom_components.ics_calendar.calendar] Familie Agenda: download_calendar start`

Other threads and add-ons kept running. After some time I got the following errors:
`Dec 13 14:29:19 homeassistant hassio_supervisor[445]: 2024-12-13 15:29:19.808 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.`

 I had 2 ics calenders via this extension, sometimes it stopped after the 'Familie Agenda', after a reboot it could be the Familie Agenda gave no problem, but my other calendar 'Avri' was the last line for the MainThread

I deleted the 'avri' line in homeassistant/.storage/core.config_entries and everything started working.

After that I added the 'avri' calendar back with a timeout option and no problems since then.

I just set the logfiles apart, but they are huge and contain private information, but if you are looking for specific parts I probably can give you that.

**Comment by JayWll** [comment]
Core 2024.12.2 and 2024.12.3
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7

Hardware: Raspberry pi 5, 8gb RAM. System installed to an NVMe drive using the HASS image from the RPi imager, ics-calendar installed via HACS.

I updated several things today, so I initially updated ics-calendar on core 2024.12.2. After I'd recovered from a backup (and before I understood what had prevented HASS from starting) I upgraded to 2024.12.3, and then again upgraded ics-calendar and experienced the same issue.

**Comment by franc6** [comment]
Thanks, @MichaKersloot That gives me an idea...

**Comment by otto2704** [comment]
hassio on proxmox
    Core 2024.12.3
    Supervisor 2024.11.4
    Operating System 14.0
    Frontend 20241127.8
    12 GB RAM
    4 cores
 same here....

**Comment by franc6** [comment]
Thanks for all the feedback, everyone!  Please reply to this if you see the problem and have only one calendar configured.
In the mean time, please give 5.0.6-beta1 a try.  This includes a change that I had originally planned to make later (or if 5.0.5-beta1 didn't work for me).  It works on my system, but again, I wasn't seeing this problem. Please reply if 5.0.6-beta1 fixes the problem.  Thank you!

**Comment by Klikini** [comment]
FWW, I had this problem with 3 calendars configured.

**Comment by Wxfisch** [comment]
I had this same issue on a Yellow standard with 2 calendars configured. I didn't connect the updating of the integration to the HA frontend crashing until I had reinstalled and restored from backup. Once I get everything stable I can give the beta a try (now that I know removing the integration from the folder will get things running again I am less hesitant to try a new version).
Not sure what your setup is, but it may be worth testing changes on setups with one and multiple calendars configured in the future to catch edge cases like this.

**Comment by WvanWaas** [comment]
1 internal and 3 external calendars in use. Just got my system back up and running with 5.0.4 might be able to do a test run?

**Comment by ingoratsdorf** [comment]
Same issue here, HA not starting, neither the LCX not the docker version after yesterday's ICS update.
Removed "ics_calendar" from custom_integrations, all good.
Only one calendar configured - as far as I can remember, LOL.

**Comment by ds-sebastian** [comment]
> Thanks for all the feedback, everyone! Please reply to this if you see the problem and have only one calendar configured. In the mean time, please give 5.0.6-beta1 a try. This includes a change that I had originally planned to make later (or if 5.0.5-beta1 didn't work for me). It works on my system, but again, I wasn't seeing this problem. Please reply if 5.0.6-beta1 fixes the problem. Thank you!

Thanks for working on this fix! However, I still had the same issues with updating to `5.0.6-beta1`. I had to revert back to `5.0.4`

**Comment by franc6** [comment]
Thanks for the testing; if @ds-sebastian still has problems, I wouldn't expect it to work for anyone else.

@Wxfisch Normally, I do have a few calendars configured with different options, but with testing for updating the configuration, I had removed the ones I don't actually use, so I could add/remove/modify them at will.  But when I ran out of time for that a while ago, I never got around to adding them back in.  There is one report of possibly only one calendar configured, but I'll see if adding more in will bring the problem up for me.  I'm 99% sure this is a problem with this integration, not with HA itself.

Sorry for all the problems, everyone.  If I can reproduce it, it'll be a lot easier to fix, and I've still got some time today and maybe tomorrow to work on it.

**Comment by franc6** [comment]
Success, sort-of.  I can reproduce the problem.

**Comment by franc6** [comment]
OK, 5.0.6-beta2 fixes the problem as I reproduced it.  I think this one will fix it for the rest of you, and it makes sense how this would cause a problem that would only be noticed with more than one calendar.  I'm still concerned, though, since @ds-sebastian noted the problem with only one calendar.

@agroszer If you have the time, please try 5.0.6-beta, in particular to be sure that the problem you reported with #117 isn't back again.  As I understand the documentation for httpx, the problem should be fixed, even though the lock code has been removed.

**Comment by michaelkastner** [comment]
Thanx @franc6!

My system is now running normally again with 5.0.6-beta2!!

**Comment by vrtareg** [comment]
I can confirm that I was able to update to 5.0.6-beta2!

**Comment by wjansenw** [comment]
Update works here as well with multiple calendars. Tnx for the fix!

**Comment by okj579** [comment]
@franc6
> Please reply to this if you see the problem and have only one calendar configured.

I have one calendar configured. 5.0.5 was broken, 5.0.6-beta2 fixed the problem

**Comment by JakobTewes** [comment]
oh nice...took me quite some time identifing this as root cause ;-).
Now switching to the beta version and hoping for more...

**Comment by stefanoklett** [comment]
Ca a big mess, it took me 1/2 day to figure out it was this plugin.
I tried deleting the folder as described, but then it prompts me to reconfigure the service and it no longer works with my constellation.
So I did a recoveri and hope for a new release that doesn't mess it up

**Comment by franc6** [comment]
Thanks for the feedback, everyone.  I want to wait to find out if this causes a regression for #117 or not.  It wasn't clear to me if the problem was too frequent connections (more likely, IMO) or too frequent requests.  If it's the former, and if httpx works how I think it does, then there won't be any regression.  If it's the latter, there is a regression, and I need to make further changes before release.

So, to be clear on the exact problem:

A while ago, a lock was added around downloads to ensure that it wasn't connecting too frequently to a server that didn't like it when several calendars were configured that were hosted on the same server.  The most recent change in 5.0.5 was to switch from using synchronous http calls in the background to using httpx and making the calls fully asynchronous.  The problem is that, in python, you have to use different classes for locks, and slightly different syntax.  Not knowing this, I just left the lock in place, and figured I'd test pulling it out later.  So what happens, is that when you have more than one calendar configured, it'll acquire the lock for downloading the first calendar, and when HA calls the update method to download for the second calendar (which happens before the first lock is released), instead of failure to acquire the lock yielding processing so it can be tried later, it deadlocks the main loop for HA, causing HA to hang. This would normally happen pretty early in HA's restart process, but could easily be delayed depending on what other components are installed and configured.  I'm not sure why this could happen as it does with only one calendar, but again, what I don't know will cause trouble. :)  So the 5.0.6-beta2 removes the lock -- it's probably not needed, but I don't know for sure.  If it turns out to be needed, I'll add it back in using the correct lock class and syntax.

If you wonder why the lock wasn't a problem with the synchronous code, well, HA invokes the synchronous calls differently, moving them off the main loop, and this integration had further protection to ensure it wasn't called on the main loop.  The extra protection from this integration actually breaks (other) things badly when the code was moved to be asynchronous, and was thus removed.

I'm sorry for all the problems, everyone, but I'm not a python developer, and what I don't know about python can cause trouble.  Really, finding this just makes me like python even less -- in more sane languages, this change couldn't have caused any trouble. :)

**Comment by Eschguy** [comment]
Thanks @franc6 for the quick fix!

**Comment by JakobTewes** [comment]
Thanks @franc6 for putting in the effort and time, you. Fully understand your perspective and really glad as your work ia more or less voluntary.

Also i‘d like to bring up, that your explanation really helped (for me) and is really a differentiator from for example the HA core developers, that provide their stuff but do not get into details or explain.

Thanks so much and keep track 🤝

**Comment by sagebind** [comment]
So I am having essentially the same issue, but I only have one calendar configured and not multiple. But in my case, it doesn't prevent HA from starting; instead it causes HA to freeze about 15 minutes after HA does start. There's no log messages around the time of freezing, instead just the whole Python process seems to freeze. In my case the HA Supervisor can't even ping the container API endpoint any more so it restarts it automatically.

I will give 5.0.6-beta2 a shot and see if it fixes my issue.

**Comment by accessfalk** [comment]
Same issue here, I could not login at all at port 8123, it was even blocked sometimes. So I was lucky that I had a recent full-backup somewhere else. A full new installation was my solution. Thanks @franc6 for your efforts to debug.

**Comment by 2600box** [comment]
I installed 5.0.6-beta2 and it fixed the issue without disrupting anything else, as far as I can tell. I have three google calendars configured. Thanks!

**Comment by ddakotac** [comment]
I can confirm that 5.0.6-beta2 solved the issue for me. I wound up removing custom integrations 1 x 1 until I isolated the one preventing boot and once I removed ICS calendar from custom_components folder it booted normally. I reinstalled 5.0.6-beta2 and am no longer having the issue. I have 2 calendars set up through the integration. Thanks for your responsiveness on this.

**Comment by mcattle** [comment]
Another confirmation of the fix.  With 4 calendars in use, and after a weekend of pulling out my hair why HA won't start, 5.0.6-beta2 fixes the problem.

**Comment by florianmulatz** [comment]
Closed - Fixed by 
https://github.com/franc6/ics_calendar/releases/tag/5.0.6-beta2

**Comment by iAmRenzo** [comment]
Any idea when the final release of 5.0.6 will be there?

**Comment by franc6** [comment]
Now that I know the cause of #205, I can feel better about releasing it. :)  I’ll do a new release as soon as I have time to work on it again, and I’m hopeful that will be later this week. With my holiday and work schedule, it’s hard to say for certain, though. Just note that it may introduce a regression for #117.
