### ISSUE TITLE
ics_calendar 5.1.0: no module named httpx_auth

### ISSUE THREAD

**Issue by tardich** [franc6/ics_calendar#213]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version: 2024.12.4

Installation Type (put an X between the square brackets for your HA):
[] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[x] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[x] x86-64

**Describe the bug**
Updated to ics_calendar 5.1.0 and when restarting, Home-Assistant complains that it can't find the module httpx_auth.

Have to rollback to ics_calendar 5.0.4 (and have ics loaded at home-assistant boot time (which I believe was fixed in ics_calendar 5.0.5)

**Comment by tardich** [comment]
In fact, it seems that ics module still needs to be loaded manually, with the addition of httpx_auth, as mentioned by @wrichter in a previous post (issue #194)

Adding these two modules at boot time allows me to use ics_calendar 5.1.0, but this should be provided by ics_calendar module as it requires them.

**Comment by wrichter** [comment]
Thanks for tracking this. I believe we are entering [Dependency Hell](https://en.wikipedia.org/wiki/Dependency_hell) here: ics_calendar has a direct dependency on the module 'ics' which in turn since version 6.1 has a dependency on the module 'httpx_auth'. These packages need to be provided in the python runtime environment , ics_calendar does not provide these packages itself. 

The dependencies required to run Home Assistant are baked into the HA container image, but these do not include neither the modules ics nor httpx_auth. And it is good practise from a security point of view to ship container images with the least amount of packages that are required.

So to fix the issue, from my point of view the options are:

- reeingineer ics_calendar not to depend on ics (unlikely, too much effort)
- ask the HA team to include ics and httpx_auth as modules in the HA container image (unlikely, since they don't need them)
- make the ics_calendar module an official HA module and thus make it part of the testing that will break if dependencies are missing, forcing the HA team to include all required dependencies  (also unlikely unless the maintainer is able to invest significant effort)
- bake your own container image that layers the prerequisite packages on the official HA container image (and rebuild it whenever a new HA release is to be deployed)
- use the workaround from (issue #194 ) to install those packages on container startup
- give up running ics_calendar in the official HA container image
- @franc6 mentioned an approach to make dependencies appear that in #194 that I did not understand nor meshes with my understanding of containers, but maybe that will fix things.

**Comment by franc6** [comment]
Take a look at this: https://community.home-assistant.io/t/docker-home-assistant-not-installing-custom-component-requirements/439930  Note the fix at the time was to upgrade pip and change how it was used. HA recently switched away from using pip and now uses uv. I wonder if this introduced a regression. Note that it affects those using docker images, not other installation methods (I stopped using docker a while ago for my HA instance ‘cause it was too difficult to keep it updated), and docker containers would need to install the dependencies to another directory, one that is writable. 

In any event, I don’t think this is my bug, but a bug in HA.

**Comment by wrichter** [comment]
Ok, I just tried to make heads or tails of the HA container build process that spans several repos... basically they use S6 as a in-container process manager. S6 then uses shell scripts to manage processes (very much like classic unix rc scripts) and the only script I could find simply launches homeassistant : https://github.com/home-assistant/core/blob/dev/rootfs/etc/services.d/home-assistant/run . So from what I understand, it would be the responsibility of the homassistant python module to ensure the requirements of the add-ons are there, but this is where I would actually have to be able to read python to progress further... https://github.com/home-assistant/core/blob/dev/homeassistant/requirements.py

**Comment by franc6** [comment]
See also #190 & #194.

**Comment by franc6** [comment]
After much pain and consideration, I've determined that I can't really work around this problem.  Please see the new notes in README.md.  I know that's not what anyone posting to this issue wants to read, but I'm stuck.  There's nothing I can do to make it work.  If you can reproduce the problem on a clean installation without any attempt to resolve this problem, please re-open https://github.com/home-assistant/core/issues/127966 with HA, or, if more appropriate, open a new issue with HA and note that the one I referenced is not fixed.
If you cannot reproduce the problem on a clean installation, then you probably need to clean up whatever changes you've made to fix or work-around this problem, uninstall this integration, and re-install it.
I'm really sorry, this isn't the way I wanted to close this issue, either.  :(
