### ISSUE TITLE
Feature: Start of Week

### ISSUE THREAD

**Issue by plvoy-de** [franc6/ics_calendar#27]
Hi there,

awesome addon for HA so far. I noticed Weeks start on Sunday though.
Maybe it would be possible in a future release to set it to either Sunday or Monday?
Thx for the great work!

**Comment by franc6** [comment]
Where do you see a start of week?  There's nothing explicit in this project that would be aware of the start of your week.  I'm not familiar with all possible ways of specifying repeat rules, but I can't imagine that specifying something repeat on "the second day of the week" would be better than specifying it repeat on "Monday" or "Tuesday", e.g.

If you are referring to something that is displaying your calendar entries in a calendar form, you need to send a feature request to the author of that software (which may be Home Assistant itself, since it now has that capability).

If you are referring to a repeat rule, then please re-open this issue and attach a sample calendar file to this entry. I'll keep track of it, and/or submit requests to the authors of the library(ies) I'm using.
