### ISSUE TITLE
Same info/readme files

### ISSUE THREAD

**Issue by robvanuden** [franc6/ics_calendar#3]
Why are there both a README.md and a info.md file?

**Comment by franc6** [comment]
HACS will display the contents of info.md, not README.md.  Github will show the contents of README.md, not info.md. Since the only info that's not relevant for HACS to display (at the present time) are the install instructions, and since I'm lazy, I just made both files identical.  In the future, the files might be different, and dealing with linked files and git can be painful, I didn't want to just link the files.
