### ISSUE TITLE
Next event data attributes for use in sensor/automation

### ISSUE THREAD

**Issue by dannytrigo** [franc6/ics_calendar#30]
Hi,

In other calendar integrations I have seen (eg. google calendar), the data of the next event is exposed as attributes, such as start_time.  I could use this to trigger automations, such as an alarm before the first meeting of the day.

However, this component doesn't seem to expose anything like that (at least not before the event starts).  Is that by design? Or something that could be added? How are others achieving sensors/automation without it?

I can work on it if its something that would be accepted

**Comment by franc6** [comment]
I don't use the google calendar platform (and I don't even have any calendars to give it a try).  Can you post a screenshot or similar so I can see what you mean?

This seems like something that ought to be in the calendar component, but I might not be understanding correctly.  The ability to trigger automations as you suggest certainly seems like a good idea.  You might be able to use HA's REST API to trigger automations with any calendar platform, but I suspect that would be very painful. :)

I'm always willing to consider PRs -- although if the functionality seems like it would go better in the calendar component, I'll likely encourage changing that, and getting the HA developers to accept the changes, rather than put it here. :)

**Comment by dannytrigo** [comment]
I've just checked the code of the google one, and it returns the next event calendar data in the event property, even if the event hasn't started yet.  Internally, HA will still set the sensor to not activated until the start time, but it will provide the next event data to trigger on the start time for example.  So it seems pretty simple to achieve with a small modification of ICSCalendarData.update.

I'll submit a PR with the change when I manage to test.

**Comment by dannytrigo** [comment]
![image](https://user-images.githubusercontent.com/7444376/121568508-c5ece180-c9ed-11eb-95ef-2fcfc0320de2.png)

**Comment by franc6** [comment]
Should be fixed by PR 31.

**Comment by wieluk** [comment]
Shoudl there be a start_time now? because for me there is none.
