### ISSUE TITLE
unable to parse ics file

### ISSUE THREAD

**Issue by fredrikbuchanan** [franc6/ics_calendar#34]
Hi. 
I have a problem with a ics file (https://www.formula1.com/calendar/Formula_1_Official_Calendar.ics) that is not parsing. and i think it is because of a text field beeing to long.
(at least according to https://icalendar.org/validator.html?url=https://www.formula1.com/calendar/Formula_1_Official_Calendar.ics)

is this something you can solve in your parser?

**Comment by cars1806** [comment]
Hey,
I have exactly the same problem with the same calendarfile.

`2021-08-04 12:26:13 ERROR (SyncWorker_5) [custom_components.ics.calendar] F1Cal: Failed to parse ICS!`

Is this fixable on your side @franc6 ?

**Comment by franc6** [comment]
@fredrikbuchanan,  @cars1806 I'm sorry, but I lost track of this.  It looks like if you switch to the BETA version, it will work.  I think I can also work around the problem in the non-BETA version, too, but it'll be a while before I can get back to it.

The length of lines has nothing to do with the problem; the problem is that whoever produced the file included multiple lines which read "METHOD:PUBLISH".  There's one before every VEVENT, and the RFC says you can only specify METHOD once per VCALENDAR.  If you know whom to contact, you might be able to get them to fix the calendar, as it's just plain wrong.  I don't know why the validator you used didn't complain, as it should have.

If you (or someone else) would like to submit a patch to work around the problem, I'd suggest looking at the code which removes the NULL characters, and add code there to remove the regular expression "^METHOD:.*$" from everywhere.  We don't use that field, so it's OK to just get rid of it globally.

**Comment by fredrikbuchanan** [comment]
Hi. I have now sent a email to the webmaster@formula1.com. and crossing my fingers for them to reply sooon
I hope you don't mind that I refered to you as my friend franc6
"Hi.
A friend of mine discovered a problem with the ics file you provide for the calendar sync that it is
malformated.
According to my friend the file includes multiple lines which read "METHOD:PUBLISH". There's one before every VEVENT, and the RFC says you can only specify METHOD once per VCALENDAR. 

please, we would really appreciate it if you could correct this so it conforms to the rfc.

sincerely
Fredrik Buchanan
home automation enthusiast
fredrik@buchanan.se
"

**Comment by cars1806** [comment]
I installed the latest beta version and now it works fine. 

Thanks for your work! I appreciate it!
