### ISSUE TITLE
Events over more Days

### ISSUE THREAD

**Issue by TVR-X** [franc6/ics_calendar#39]
Hallo,
i have the problem that events that are longer than one day are only displayed on the first day.
Is this an "error" or is there an option for it and I just couldn't find it?

**Comment by franc6** [comment]
It depends. The display of events in a calendar is outside the scope of the platform. If you mean that it doesn’t show as the current event when you look at the generated sensor, then it’s probably a bug in this software — I’d have to play with it to see how the current event is requested.

In the mean-time, if your event is all day and lasts multiple days, you might be able to work around the problem by specifying the event as all-day and repeating, rather than a duration of multiple whole days. That might not be ideal if, for example, the event is tied to a particular time zone, but if not, it may be a better way to specify it. :)

**Comment by TVR-X** [comment]
Ok, its a probelm in the calendar month and week view. list or day view is ok.
i think this can be closed because its not a problem of this integration.
