### ISSUE TITLE
Feature Request: Upcoming Events

### ISSUE THREAD

**Issue by Ra7t0r** [franc6/ics_calendar#59]
Hello.
It should be great if there is the option to get upcoming events (etc next day or next 2 days) and return these entries  in order to use within a card on Dashboard.
In this way, It should be easy to identify next day events and create automations.

Something like this:

![](https://im4.ezgif.com/tmp/ezgif-4-f9f361fc5b.gif)

**Comment by franc6** [comment]
While I like the idea, this isn't the right place to request such a feature.  This project is just a platform for the calendar entity in Home Assistant.  Please request the feature in Home Assistant first; if it's added, there's a good chance it will "just work", since there are already ways to get the relevant information from any calendar platform.  If, however, Home Assistant were to implement a feature in a manner that requires changes to individual calendar platforms, I would, of course, update this one to implement the feature.  :)

In the meantime, however, you can develop automations based on future events by using the Home Assistant API for calendars (&lt;URL of home assistant&gt;/api/calendars/&lt;calendar name&gt;?start=2022-01-01T00:00:00Z&end=2022-01-01T23:59:59Z to get get all events for Jan 1, 2022, UTC).  Another choice, is if you have access to the Home Assistant object (e.g. in a python script), you might be able to invoke the calendar's async_get_events() method (see https://developers.home-assistant.io/docs/core/entity/calendar/), to get the events.

Unfortunately, neither of those methods are easy or even simple when trying to do automations.  You would need to ensure your script that gets events does so regularly, and sets a sensor, and use that for your automation trigger.  Additional sensors could include the relevant event data.  I would recommend writing a custom component that would set up sensors to be used as a trigger and for the actual event data.  Such a component would work with **any** calendar platform, not just this one.  I'd also recommend sharing the component with everyone else. :)
