### ISSUE TITLE
match case not compatible with Python 3.9

### ISSUE THREAD

**Issue by poja1993** [franc6/ics_calendar#60]
In custom_components/ics_calendar/filter.py a match case (line 45) is present. This is included from Python 3.10.
I didn't see it mentioned in the breaking changes :(

**Comment by franc6** [comment]
I’m sorry. I forgot to bump the HA requirement for that version, which would have hidden the problem from most users who aren’t running python 3.10, since that’s been required since 2022.7. :(

I’ll update the HA requirement when I can get back to this (probably sometime on 2022-08-02 in US EDT), and update the changelig to indicate the break. 

I’m really not interested in making it work with older versions of python, especially when it’s to avoid a language feature whose lack has frustrated me many times in the past. :)

**Comment by franc6** [comment]
Requirements have been updated, Breaking Changes section has been updated to reflect this breaking change.  Release 3.1.0 has been removed, and replaced by 3.1.1, in the hopes that nobody else will be bitten by the incorrect 3.1.0 release, like you were. :(
Please accept my apologies for the error.
