### ISSUE TITLE
Request: Support for unique_id

### ISSUE THREAD

**Issue by metbril** [franc6/ics_calendar#81]
It would be really nice if the integration supported `unique_id`, so the entity can be managed through the UI (icon, friendly name, entity id, etc.)

**Comment by franc6** [comment]
This won't do what you expect.  To manage the entities through the UI, the integration would need to support Config Flow, which I'd like to support.  Unfortunately, to support Config Flow, the main HA calendar device type would need to be updated to support it, too, or I'd have to implement a new device type (which doesn't make logical sense).  Since HA doesn't support Config Flow for calendar yet, I'm stuck with requiring configuration be through the YAML file.  There are also no suitable unique identifiers using the YAML configuration.  Please note that a URL is explicitly "unacceptable", but is also the only unique data in the YAML configuration.
Once Config Flow is an option, unique_id will also be generated.

**Comment by metbril** [comment]
Sorry to find you closing the issue. I find it hard to understand that config flow is required. There are multiple examples of (native) integrations that need to be configured using YAML, but still support a unique ID. For example, the generic thermostat: https://www.home-assistant.io/integrations/generic_thermostat/

I hope you will reconsider this and re-open the issue.

**Comment by franc6** [comment]
Please review the documentation at https://developers.home-assistant.io/docs/development_index.  While the integration you mention does have an entry for unique_id, doing that is no longer allowed.  The documentation is very clear that the unique_id attribute must not be something that can be modified by an end user.  Additionally, allowing it to be set in YAML that way will cause headaches for everyone who set it when the platform eventually can use Config Flow. I recommend being patient, or write your own.  It's easy to fork this project and add the approximately 4 lines of code that will eventually cause problems for you, if you want to keep getting updates. ;)
