### ISSUE TITLE
Cannot set unique_id for calendar entities

### ISSUE THREAD

**Issue by codyc1515** [franc6/ics_calendar#89]
Because a `unique_id` cannot be set in the configuration.yaml file, the entities cannot be controlled in the Lovelace UI. Is it possible to add support for the `unique_id` value?

**Comment by lunarok** [comment]
I have the same request, will be a great feature. Calendars are last piece in my config that could not be hide from lovelace UI

**Comment by sda3-14** [comment]
Why can't we use a URL as an identifier? I understand why IP address, device name and hostname shouldn't be used (for local devices), since they can always be easily changed by the user. But in our case, the URL will always 100% uniquely identify the calendar - i think this might refer more to local devices (IP addresses might change, so it's disallowed). The only thing I would change is adding the username as well, since some services might have an endpoint like https://example.org/api/mycalendar.ics where it's the same endpoint for every user, and the result only changes based on the auth.

**Comment by franc6** [comment]
Please note that you might change the URL over time, and the unique ID is supposed to be a constant.  So using the URL is a non-starter.

However, with version 5.0.0, this won't be a problem, as a unique id will be assigned by HA itself.
