### ISSUE TITLE
Support webcal URLs

### ISSUE THREAD

**Issue by Atriusftw** [franc6/ics_calendar#94]
I'm trying to use this integration to import events from an ical provided through webcal, however i get this error in the logs:

Logger: custom_components.ics_calendar.calendar
Source: custom_components/ics_calendar/calendardata.py:73
Integration: ics_calendar ([documentation](https://github.com/franc6/ics_calendar), [issues](https://github.com/franc6/ics_calendar/issues))
First occurred: 20:09:57 (55 occurrences)
Last logged: 20:42:02
`<my calendar entity>: Failed to open url: unknown url type: webcal`

Is this something that can be supported or am i on the wrong tracks here?

**Comment by franc6** [comment]
Try replacing “webcal://“ with “https://“. webcal isn’t its own URI scheme, and it looks like it’s usually treated as caldav, but I don’t know your specific use case.  If https doesn’t work, try using the CalDAV platform instead of this project. On Jun 21, 2023, at 2:57 PM, Marius ***@***.***> wrote:﻿
I'm trying to use this integration to import events from an ical provided through webcal, however i get this error in the logs:
Logger: custom_components.ics_calendar.calendar
Source: custom_components/ics_calendar/calendardata.py:73
Integration: ics_calendar (documentation, issues)
First occurred: 20:09:57 (55 occurrences)
Last logged: 20:42:02
<my calendar entity>: Failed to open url: unknown url type: webcal
Is this something that can be supported or am i on the wrong tracks here?

**Comment by Atriusftw** [comment]
Thanks. I ended up using another integration for my use case though.
